Baseline 1.20

diff --git a/third-party/qthread/Makefile b/third-party/qthread/Makefile
--- a/third-party/qthread/Makefile
+++ b/third-party/qthread/Makefile
@@ -24,34 +24,71 @@ else ifneq ($(CHPL_MAKE_HOST_PLATFORM),$(CHPL_MAKE_TARGET_PLATFORM))
 CHPL_QTHREAD_CFG_OPTIONS += --host=$(CHPL_MAKE_TARGET_PLATFORM)-unknown-linux-gnu
 endif
 
-ifeq ($(CHPL_MAKE_HWLOC),hwloc)
-CHPL_QTHREAD_CFG_OPTIONS += --with-topology=hwloc --with-hwloc=$(HWLOC_INSTALL_DIR)
-endif
-ifeq ($(CHPL_MAKE_HWLOC),system)
-CHPL_QTHREAD_CFG_OPTIONS += --with-topology=hwloc
+ifneq ($(CHPL_MAKE_HWLOC),none)
+  # Have Qthreads get its hwloc topology from the Chapel runtime,
+  # unless directed not to.
+  ifeq (, $(call isTrue, $(CHPL_QTHREAD_DONT_GET_TOPO_FROM_RT)))
+    CHPL_QTHREAD_CFG_OPTIONS += --with-topology=hwloc_via_chapel
+    CFLAGS_NEEDS_RT_INCLUDES = y
+  else
+    CHPL_QTHREAD_CFG_OPTIONS += --with-topology=hwloc
+  endif
+  ifeq ($(CHPL_MAKE_HWLOC),hwloc)
+    CHPL_QTHREAD_CFG_OPTIONS += --with-hwloc=$(HWLOC_INSTALL_DIR)
+  endif
 endif
 
 
 # Have qthreads use Chapel's allocator, unless directed not to
 ifeq (, $(call isTrue, $(CHPL_QTHREAD_NO_CHPL_ALLOC)))
-CHPL_QTHREAD_CFG_OPTIONS += --with-alloc=chapel
-CFLAGS += -I$(CHPL_MAKE_HOME)/runtime/include/mem/$(CHPL_MAKE_MEM)/
-CFLAGS += -I$(CHPL_MAKE_HOME)/runtime/include/
-ifeq ($(CHPL_MAKE_MEM),jemalloc)
-CFLAGS += -I$(JEMALLOC_INCLUDE_DIR)
-RUNTIME_LFLAGS += -L$(JEMALLOC_LIB_DIR)
-RUNTIME_LFLAGS += -ljemalloc
-RUNTIME_LFLAGS += $(shell $(JEMALLOC_BIN_DIR)/jemalloc-config --libs)
-endif
+  CHPL_QTHREAD_CFG_OPTIONS += --with-alloc=chapel
+  CFLAGS_NEEDS_RT_INCLUDES = y
 endif
 
-# enable oversubscription for testing
-ifneq (, $(CHPL_QTHREAD_ENABLE_OVERSUBSCRIPTION))
-CHPL_QTHREAD_CFG_OPTIONS += --enable-oversubscription
+FAILBUILD=
+ifeq ($(CFLAGS_NEEDS_RT_INCLUDES), y)
+  #
+  # When building the Chapel allocator file we need all the Chapel runtime
+  # defs and include directories, plus the third-party include dirs other
+  # than that for Qthreads itself (since we're building it).  Notably, we
+  # do not want -DNDEBUG; if we have that set when building Qthreads it
+  # seems to cause Chapel programs built with the result to hang during
+  # exit when shutting down Qthreads.
+  #
+  # Note that we call compileline with CHPL_MAKE_COMM=none. Under
+  # CHPL_MAKE_COMM=gasnet, compileline will fail if gasnet is not built,
+  # so in order to avoid ordering/dependencies just ignore the comm
+  # setting since it does not impact the qthreads build. We don't want
+  # to reset the CHPLENV_CACHE since the regular CHPL_COMM setting could
+  # impact things like CHPL_TARGET_CPU, which is part of the build path
+  #
+  # Throw COMPILELINE_STDERR_REDIRECT= if compileline failure is reported
+  # and you want to see the stderr from that.
+  #
+  COMPILELINE_STDERR_REDIRECT=2> /dev/null
+  COMM_NONE_CHPLENV_CACHE := $(shell echo "$(CHPL_MAKE_CHPLENV_CACHE)" | sed 's/|CHPL_MAKE_COMM=[^|]*|/|CHPL_MAKE_COMM=none|/')
+  INCS_DEFS := \
+    $(shell CHPL_HOME=$(CHPL_MAKE_HOME) CHPL_MAKE_CHPLENV_CACHE="$(COMM_NONE_CHPLENV_CACHE)" $(CHPL_MAKE_HOME)/util/config/compileline --includes-and-defines \
+               $(COMPILELINE_STDERR_REDIRECT) \
+            || echo compilelineFAILURE)
+  ifneq (, $(findstring compilelineFAILURE,$(INCS_DEFS)))
+    FAILBUILD=y
+  else
+    INCS_DEFS_PROCESSED := \
+      $(shell echo $(INCS_DEFS) \
+              | tr ' ' '\n' \
+              | grep '^-DCHPL\|/runtime//*include\|/third-party/.*/install' \
+              | grep -v '/third-party/qthread/install' \
+              | tr '\n' ' ' \
+              | sed 's/ $$//')
+    CFLAGS += $(INCS_DEFS_PROCESSED)
+  endif
 endif
 
 # enable guard pages for stack overflow detection, unless directed not to
+HAVE_GUARD_PAGES = 0
 ifeq (, $(call isTrue, $(CHPL_QTHREAD_NO_GUARD_PAGES)))
+HAVE_GUARD_PAGES = 1
 CHPL_QTHREAD_CFG_OPTIONS += --enable-guard-pages
 endif
 
@@ -87,6 +124,10 @@ ifneq (, $(findstring pgi,$(CHPL_MAKE_TARGET_COMPILER)))
 CHPL_QTHREAD_CFG_OPTIONS += --disable-internal-spinlock
 endif
 
+ifeq ($(CHPL_LIB_PIC),pic)
+CFLAGS += $(SHARED_LIB_CFLAGS)
+endif
+
 CHPL_QTHREAD_CFG_OPTIONS += $(CHPL_QTHREAD_MORE_CFG_OPTIONS)
 
 default: all
@@ -104,6 +145,8 @@ clobber: FORCE
 
 
 qthread-config: FORCE
+	@test -z "$(FAILBUILD)" || ( echo 'compileline failed!' && false )
+
 #
 # These first few lines touch a bunch of autoconf-oriented files in a
 # certain order to prevent autoconf from running again; otherwise, we
@@ -144,21 +187,24 @@ qthread-build: FORCE
 # we'll need separate checks to set them.
 #
 ifeq ($(SCHEDULER),$(findstring $(SCHEDULER),lifo mtsfifo mutexfifo nemesis))
-SUPPORTS_REMOTE_CACHE = 1
 ONE_WORKER_PER_SHEPHERD = 1
+TASKS_CAN_MIGRATE_THREADS = 0
 else ifeq ($(SCHEDULER),$(findstring $(SCHEDULER),distrib nottingham sherwood))
-SUPPORTS_REMOTE_CACHE = 0
 ONE_WORKER_PER_SHEPHERD = 0
+TASKS_CAN_MIGRATE_THREADS = 1
 else
 $(error Unrecognized Qthreads scheduler '$(SCHEDULER)')
 endif
 
 qthread-chapel-h: FORCE
-	echo "#define CHPL_QTHREAD_SUPPORTS_REMOTE_CACHE" \
-	     $(SUPPORTS_REMOTE_CACHE) \
-	     > $(QTHREAD_INSTALL_DIR)/include/qthread-chapel.h
 	echo "#define CHPL_QTHREAD_SCHEDULER_ONE_WORKER_PER_SHEPHERD" \
 	     $(ONE_WORKER_PER_SHEPHERD) \
+	     > $(QTHREAD_INSTALL_DIR)/include/qthread-chapel.h
+	echo "#define CHPL_QTHREAD_TASKS_CAN_MIGRATE_THREADS" \
+	     $(TASKS_CAN_MIGRATE_THREADS) \
+	     >> $(QTHREAD_INSTALL_DIR)/include/qthread-chapel.h
+	echo "#define CHPL_QTHREAD_HAVE_GUARD_PAGES" \
+	     $(HAVE_GUARD_PAGES) \
 	     >> $(QTHREAD_INSTALL_DIR)/include/qthread-chapel.h
 
 qthread: qthread-config qthread-build qthread-chapel-h
