Pushing out QSBR files

diff --git a/util/buildRelease/smokeTest b/util/buildRelease/smokeTest
--- a/util/buildRelease/smokeTest
+++ b/util/buildRelease/smokeTest
@@ -45,6 +45,15 @@ if (( $num_tabs > 0 )) ; then
     exit 1
 fi
 
+# Need to clean up all of the trailing spaces before adding this
+# Check for trailing spaces
+#num_trailing_space_lines=$($CHPL_HOME/util/devel/lookForTrailingSpaces | wc -l)
+#if (( $num_trailing_space_lines > 0 )) ; then
+#    echo "Found $num_trailing_space_lines lines with trailing spaces :-("
+#    echo $($CHPL_HOME/util/devel/lookForTrailingSpaces)
+#    exit 1
+#fi
+
 # Check for standard C headers.
 standard_c_headers=$($CHPL_HOME/util/devel/grepstdchdrs || :)
 if [ -n "${standard_c_headers}" ] ; then
@@ -106,11 +115,16 @@ num_procs=$(python -c "import multiprocessing; print(multiprocessing.cpu_count()
 # in $CHPL_HOME where the hello*.chpl tests are copied and run.
 export CHPL_CHECK_INSTALL_DIR=$CHPL_HOME
 
-if [ "${TRAVIS}" = "true" ] ; then
-    export CHPL_CHECK_INSTALL_PRINT_ERROR="true"
+if [ "${CHPL_SMOKE_SKIP_MAKE_CHECK}" != "true" ] ; then
+    # Compile chapel and make sure `make check` works. Compile first with parallel
+    # execution, but call `make check` without it.
+    make -j${num_procs} $chpl_make_args && \
+        CHPL_CHECK_DEBUG=1 make $chpl_make_args check || exit 2
 fi
 
-# Compile chapel and make sure the hello world examples run. Compile first with
-# parallel execution, but call `make check` without it.
-make -j${num_procs} $chpl_make_args && \
-    make $chpl_make_args check
+if [ "${CHPL_SMOKE_SKIP_DOC}" != "true" ] ; then
+    # Build chpldoc, make sure the chpldoc primer runs, and the docs build.
+    make -j${num_procs} $chpl_make_args chpldoc && \
+        make $chpl_make_args check-chpldoc && \
+        make docs || exit 2
+fi
diff --git a/util/buildRelease/testReleaseHelp b/util/buildRelease/testReleaseHelp
--- a/util/buildRelease/testReleaseHelp
+++ b/util/buildRelease/testReleaseHelp
@@ -60,6 +60,23 @@ if ($tmpstatus != 0) then
     exit($tmpstatus)
 endif
 
+# Build chpldoc and run chpldoc-check.
+$mymake -j$num_procs chpldoc
+set tmpstatus = $status
+if ($tmpstatus != 0) then
+    echo "ERROR: make chpldoc failed"
+    exit($tmpstatus)
+endif
+rehash   # required for csh only; if we convert this to bash, drop this
+
+$mymake check-chpldoc
+set tmpstatus = $status
+if ($tmpstatus != 0) then
+    echo "ERROR: make check-chpldoc failed"
+    exit($tmpstatus)
+endif
+
+
 # Calculate expected version string from version_num.h.
 set major=`cat compiler/main/version_num.h | grep MAJOR_VERSION | cut -f3 -d' ' | sed 's/\"//g'`
 set minor=`cat compiler/main/version_num.h | grep MINOR_VERSION | cut -f3 -d' ' | sed 's/\"//g'`
@@ -67,7 +84,7 @@ set patch=`cat compiler/main/version_num.h | grep UPDATE_VERSION | cut -f3 -d' '
 set expected_version_string="$major.$minor.$patch"
 
 # Test chpl --version for expected string version.
-set version_string = `chpl --version | grep 'Version' | cut -d' ' -f 3`
+set version_string = `chpl --version | grep 'version' | cut -d' ' -f 3`
 set versionstatus = $status
 if ($versionstatus != 0) then
     echo "ERROR: execution of chpl --version failed"
@@ -83,6 +100,11 @@ endif
 #
 cd examples
 $mymake -j$num_procs
+set tmpstatus = $status
+if ($tmpstatus != 0) then
+    echo "ERROR: compiling examples with 'make' failed"
+    exit($tmpstatus)
+endif
 cd ..
 
 
@@ -95,7 +117,15 @@ if ($tmpstatus != 0) then
     echo "ERROR: cd into examples failed"
     exit($tmpstatus)
 endif
-./start_test -logfile Logs/testReleaseHelp.log
+
+set start_test_flags = ''
+if ($?CHPL_TEST_RELEASE_NORECURSE) then
+    set start_test_flags = ${start_test_flags}' --norecurse'
+endif
+
+./start_test ${start_test_flags} -logfile Logs/testReleaseHelp.log
+
+endif
 set tmpstatus = $status
 if ($tmpstatus != 0) then
     echo "ERROR: testing of examples failed"
diff --git a/util/pastPerformance/testReleasesPerformance b/util/pastPerformance/testReleasesPerformance
--- a/util/pastPerformance/testReleasesPerformance
+++ b/util/pastPerformance/testReleasesPerformance
@@ -3,12 +3,29 @@
 #
 # Use this script to generate performance for the current suite of
 # tests across the past several releases (those that are outlined
-# below).  
+# below).
 #
 # To use it:
 #
+# * note that this script is currently hard-coded to our usage of it
+#   at Cray in terms of referring to certain paths and pre-installed
+#   locations of past releases.  With more effort, it could be
+#   parameterized for external users, if desired.
+#
 # * set CHPL_HOME to indicate the current CHPL_HOME that you want to
-#   use (from which the util/ scripts will be used)
+#   use.  This hierarchy's util/ scripts will be used to run the
+#   tests.
+#
+# * NOTE: To get results that are optimal / comparable to those
+#   obtained in nightly performance runs, you need to host your
+#   $CHPL_HOME from a local disk like /tmp rather than from an
+#   NFS-mounted directory (BRAD: This means you, dummy).
+#
+# * make sure that your $CHPL_HOME is set up to run testing (e.g.,
+#   can you run 'start_test'?)  If not, do a normal 'make test-venv'.
+#
+# * optionally, set CHPL_TEST_VENV_DIR if you want it to differ
+#   from the default below.
 #
 # * optionally, set CHPL_TEST_PERF_DIR to indicate where you want
 #   the output .dat and html/ files to be placed.  By default, it
@@ -19,12 +36,15 @@
 #   in a normal test run, this will test all subdirectories under the
 #   cwd.
 #
+# * the script will then run the current performance tests across all
+#   past releases.
+#
 
 function testReleasePerformance {
     pushd $CHPL_HOME
     . util/setchplenv.bash
     popd
-    $CHPL_HOME_ORIG/util/start_test -performance -num-trials 3
+    $CHPL_TEST_UTIL_DIR/start_test -performance --compopts --no-cc-warnings -num-trials 3
 }
 
 if [[ -z $CHPL_HOME ]]; then
@@ -33,6 +53,19 @@ fi
 
 export CHPL_HOME_ORIG=$CHPL_HOME
 export CHPL_TEST_UTIL_DIR=$CHPL_HOME_ORIG/util
+
+if [[ -z $CHPL_TEST_VENV_DIR ]]; then
+    python_version_dir=py`$CHPL_TEST_UTIL_DIR/chplenv/chpl_python_version.py`
+    if [[ -z $CHPL_HOST_PLATFORM ]]; then
+        export CHPL_TEST_VENV_DIR=$CHPL_HOME_ORIG/third-party/chpl-venv/install/`$CHPL_TEST_UTIL_DIR/chplenv/chpl_platform.py --host`/$python_version_dir/chpl-virtualenv
+    else
+        export CHPL_TEST_VENV_DIR=$CHPL_HOME_ORIG/third-party/chpl-venv/install/$CHPL_HOST_PLATFORM/$python_version_dir/chpl-virtualenv
+    fi
+fi
+if [[ ! -d $CHPL_TEST_VENV_DIR ]]; then
+    echo "ERROR: incorrect or missing CHPL_TEST_VENV_DIR='$CHPL_TEST_VENV_DIR'"
+    exit 1
+fi
 
 #
 # This is a place where all releases will be unpacked and built with
@@ -70,12 +103,42 @@ export CHPL_TEST_PERF_DATE="09/22/14"
 export CHPL_HOME=$chpl_release_home/chapel-1.10.0
 testReleasePerformance
 
+export CHPL_TEST_PERF_DATE="03/25/15"
+export CHPL_HOME=$chpl_release_home/chapel-1.11.0
+testReleasePerformance
+
+export CHPL_TEST_PERF_DATE="09/24/15"
+export CHPL_HOME=$chpl_release_home/chapel-1.12.0
+testReleasePerformance
+
+export CHPL_TEST_PERF_DATE="03/29/16"
+export CHPL_HOME=$chpl_release_home/chapel-1.13.1
+testReleasePerformance
+
+export CHPL_TEST_PERF_DATE="09/27/16"
+export CHPL_HOME=$chpl_release_home/chapel-1.14.0
+testReleasePerformance
+
+export CHPL_TEST_PERF_DATE="03/27/17"
+export CHPL_HOME=$chpl_release_home/chapel-1.15.0
+testReleasePerformance
+
+export CHPL_TEST_PERF_DATE="09/27/17"
+export CHPL_HOME=$chpl_release_home/chapel-1.16.0
+testReleasePerformance
+
 #
-# ADD NEW RELEASES HERE AS THEY ARE CREATED.  
+# ADD NEW RELEASES HERE AS THEY ARE CREATED.
 #
 # (The date should be the date of the release branch, which should
 # match the date in $CHPL_HOME/util/test/perf/perfgraph.js)
 #
+
+unset CHPL_TEST_PERF_DATE
+export CHPL_HOME=$CHPL_HOME_ORIG
+$CHPL_TEST_UTIL_DIR/start_test --gen-graphs
+
+
 
 
 
diff --git a/util/test/checkChplInstall b/util/test/checkChplInstall
--- a/util/test/checkChplInstall
+++ b/util/test/checkChplInstall
@@ -1,15 +1,16 @@
 #!/usr/bin/env bash
+
+# Validate Chapel installation by compiling and executing an example job.
 #
-# Portable script to validate chapel installation by compiling and executing
-# the hello world examples. Exits with zero status code when compilation and
-# execution work as expected. Expects that chpl is available on the PATH and
-# that CHPL_HOME is set correctly.
 #
-# This is morally equivalent to running start_test against the
-# examples/hello*.chpl tests. It works by copying the tests from $CHPL_HOME,
-# which can either be an installation from source/rpm or a working copy of the
-# source repo, to a temporary directory in $HOME/.chpl/. start_test is then run
-# from that temporary directory.
+# Exits with zero status code when compilation and execution work as
+# expected. Expects that chpl is available on the PATH and that CHPL_HOME is
+# set correctly.
+#
+# It works by copying the test from $CHPL_HOME, which can  either be an
+# installation from source/rpm or a working copy of the source repo, to a
+# temporary directory in $HOME/.chpl/, then executing the binary and diffing
+# the output with the .good file.
 #
 # Using a temporary directory is necessary for most installations, since the
 # user running the tests will not have the permissions to modify $CHPL_HOME
@@ -23,201 +24,252 @@
 #
 # To use something other than $HOME/.chpl, set the CHPL_CHECK_INSTALL_DIR
 # environment variable.
-#
-# To have the start_test logs printed when one or more tests fail, set
-# CHPL_CHECK_INSTALL_PRINT_ERROR to "true". The log file will be kept in
-# $CHPL_CHECK_INSTALL_DIR when there are failures, regardless of the print
-# error setting.
-#
-# There is an undocumented --debug flag, which is useful for development. It
-# produces more verbose output and does not delete the temporary working
-# directory when the script exits.
+
+function log_info()
+{
+    local msg=$@
+    echo "[Info] ${msg}"
+}
+
+function log_warning()
+{
+    local msg=$@
+    echo "[Warn] ${msg}"
+}
+
+function log_error()
+{
+    local msg=$@
+    echo "[Fail] ${msg}" >&2
+}
 
 function log_debug()
 {
     local msg=$@
-    if [ -n "${debug_chpl_test}" ] ; then
-        echo "[DEBUG] ${msg}"
+    if [ "${CHPL_CHECK_DEBUG}" == "1" ]; then
+        echo "[Debug] ${msg}" >&2
     fi
 }
-function log_error()
-{
-    local msg=$@
-    echo "[ERROR] ${msg}" 1>&2
-}
 
-case $1 in
-    "")
-        # nothing special when no args are given
-        ;;
-    --debug)
-        debug_chpl_test=true
-        ;;
-    --help|-h|*)
-        cat<<EOF
-usage: $0
+log_debug "Starting \"make check\" script."
+log_debug "Debug output is turned on, because \$CHPL_CHECK_DEBUG == 1"
 
-  Runs hello world example programs to verify chpl installation is working
-  correctly. Exits with zero status code when successful. Expects chpl to be on
-  the PATH and CHPL_HOME to be set correctly.
+# Base name for test job in examples
+TEST_JOB_BASENAME=hello6-taskpar-dist
 
-  By default, programs are compiled and run from \$HOME/.chpl/. Set
-  CHPL_CHECK_INSTALL_DIR environment variable to use an alternate location.
+# Notify user we are running this script
+log_info "Running minimal test script: \$CHPL_HOME/util/test/checkChplInstall"
 
-EOF
-        exit 0
-        ;;
-esac
+BIN_NAME=chpl
 
-CHPL_BIN=$(which chpl 2> /dev/null)
+CHPL_BIN="$(which ${BIN_NAME} 2> /dev/null)"
 
-# Verify chpl binary exists and is executable.
+# Verify chpl is in $PATH
 if [ -z "${CHPL_BIN}" ] ; then
-    log_error "chpl compiler not found. Make sure it available in the current PATH."
+    log_error "${BIN_NAME} not found. Make sure it available in the current PATH."
     exit 1
-elif [ ! -x $CHPL_BIN ] ; then
-    log_error "Found chpl at ${CHPL_BIN} but it is not executable."
+elif [ ! -x ${CHPL_BIN} ] ; then
+    log_error "Found ${BIN_NAME} at ${CHPL_BIN} but it is not executable."
     exit 1
 else
-    log_debug "Found chpl compiler at: ${CHPL_BIN}"
+    log_info "Found executable ${BIN_NAME} in ${CHPL_BIN}."
 fi
 
 # Verify CHPL_HOME is correctly set.
-if [ -z "${CHPL_HOME+x}" ] ; then
+if [ -z "${CHPL_HOME}" ] ; then
     log_error "CHPL_HOME is not set in environment."
     exit 1
-elif [ ! -d $CHPL_HOME ] ; then
+elif [ ! -d ${CHPL_HOME} ] ; then
     log_error "CHPL_HOME is not a directory: ${CHPL_HOME}"
     exit 1
 else
-    log_debug "CHPL_HOME is set to: ${CHPL_HOME}"
+    log_info "Found \$CHPL_HOME directory: ${CHPL_HOME}"
 fi
 
-# Find examples test directory.
-if [ -d $CHPL_HOME/test/release/examples ] ; then
+# Create ~/.chpl directory, if it does not already exist
+CHPL_DIR=${CHPL_CHECK_INSTALL_DIR:-${HOME}/.chpl}
+if [ ! -d ${CHPL_DIR} ] ; then
+    log_info "${CHPL_DIR} does not exist. Creating it."
+    mkdir -p ${CHPL_DIR} || { log_error "Failed to create ${CHPL_DIR}." && exit 1 ; }
+    CHPL_DIR_REMOVE=1
+else
+    log_info "${CHPL_DIR} already exists. Using it."
+    CHPL_DIR_REMOVE=0
+fi
+( cd "${CHPL_DIR}" ) || { log_error "failed cd $CHPL_DIR" ; exit 1 ; }
+
+# Tmp directory for compile output
+TMP_TEST_DIR="$(mktemp -d ${CHPL_DIR}/chapel-test-XXXXX)"
+if [ -z "${TMP_TEST_DIR}" ] ; then
+    log_error "failed mktemp -d ${CHPL_DIR}/chapel-test-XXXXX"
+    exit 1
+fi
+log_info "Temporary test job directory: ${TMP_TEST_DIR}"
+( cd ${TMP_TEST_DIR} ) || { log_error "failed cd ${TMP_TEST_DIR}" ; exit 1 ; }
+
+# Cleanup the tmp directory whenever exit is invoked
+function cleanup_tmp_dir()
+{
+    log_debug "Removing ${TMP_TEST_DIR}"
+    local i
+    # sometimes on an NFS file system, rm needs to wait for the TEST_JOB exe file to close
+    for i in 1 2 3 4 5
+    do
+        rm -rf ${TMP_TEST_DIR} && break
+        log_warning "failed rm -rf ${TMP_TEST_DIR}, wait and try again"
+        ( set -x; ls -la ${TMP_TEST_DIR} ) || : ok
+        sleep 1
+    done
+    rm -rf ${TMP_TEST_DIR} || (
+        log_warning "Failed to remove ${TMP_TEST_DIR}. Please remove this directory manually."
+        set -x; ls -la ${TMP_TEST_DIR}
+    ) || : ok
+    if [ "${CHPL_DIR_REMOVE}" == "1" ]; then
+        log_debug "Removing ${CHPL_DIR}"
+        # rmdir should fail if some other process started using CHPL_DIR after we created it
+        rmdir ${CHPL_DIR} || log_debug "rmdir error ignored"
+    fi
+}
+trap cleanup_tmp_dir EXIT
+
+# Location of test job
+if [ -d ${CHPL_HOME}/test/release/examples ] ; then
     # Install from source repo.
-    TEST_DIR=$CHPL_HOME/test/release/examples
-elif [ -d $CHPL_HOME/examples ] ; then
+    TEST_DIR=${CHPL_HOME}/test/release/examples
+    REL_TEST_DIR=test/release/examples
+elif [ -d ${CHPL_HOME}/examples ] ; then
     # Install from tarball.
-    TEST_DIR=$CHPL_HOME/examples
+    TEST_DIR=${CHPL_HOME}/examples
+    REL_TEST_DIR=examples
 else
     log_error "Could not find test cases in CHPL_HOME: ${CHPL_HOME}."
     exit 1
 fi
 
-# List all the files in the examples dir. Do not list any subdirectories,
-# though.
-TESTS=$(find $TEST_DIR -maxdepth 1 -mindepth 1 -type f)
+TEST_JOB=${TEST_JOB_BASENAME}
 
-# Copy these tests to a temp file.
-
-chpl_dir=${CHPL_CHECK_INSTALL_DIR:-$HOME/.chpl}
-if [ ! -d $chpl_dir ] ; then
-    log_debug "${chpl_dir} does not exist. Creating it."
-    # Do not use -p/--parents. $HOME should exist and if it doesn't many other
-    # things will probably fail.
-    mkdir $chpl_dir || { log_error "Failed to create ${chpl_dir}." && exit 10 ; }
+if [ "${CHPL_CHECK_DEBUG}" == 1 ] ; then
+    log_debug "printchplenv, because \$CHPL_CHECK_DEBUG == 1"
+    $CHPL_HOME/util/printchplenv
 fi
 
-TMP_TEST_DIR=$(mktemp -d ${chpl_dir}/chapel-test-XXXXX)
-log_debug "TMP_TEST_DIR: ${TMP_TEST_DIR}"
+# Collect comm protocol environment variables (lowercase to avoid conflicts)
+chpl_comm="$($CHPL_HOME/util/chplenv/chpl_comm.py)"
+chpl_launcher="$($CHPL_HOME/util/chplenv/chpl_launcher.py)"
 
-# Ensure the tmp dir is deleted when script exits.
-function cleanup_tmp_dir()
-{
-    # Leave the directory when using --debug.
-    if [ -z "${debug_chpl_test}" ] ; then
-        rm -rf $TMP_TEST_DIR || :
-    else
-        log_debug "Leaving tmp test dir: ${TMP_TEST_DIR}"
-    fi
-}
-trap cleanup_tmp_dir EXIT
+# Necessary to suppress warnings when WARNINGS=1 (e.g. nightly build settings)
+COMP_FLAGS="--cc-warnings"
 
-test_output_log=$TMP_TEST_DIR/test_output.log
-cp $TESTS $TMP_TEST_DIR/
+# Compile test job into temporary directory
+log_info "Compiling \$CHPL_HOME/${REL_TEST_DIR}/${TEST_JOB}.chpl"
+TEST_COMP_OUT=$( ${CHPL_BIN} ${TEST_DIR}/${TEST_JOB}.chpl ${COMP_FLAGS} -o ${TMP_TEST_DIR}/${TEST_JOB} 2>&1 )
+COMPILE_STATUS=$?
 
-# Move to the temp directory and run the tests!
-(
-    cd $TMP_TEST_DIR
-    export CHPL_TEST_UTIL_DIR=$CHPL_HOME/util
+# Check that compile was successful
+log_debug "Compilation exit status was ${COMPILE_STATUS}"
 
-    # Run the tests.
-    echo "Running the hello world tests found in: $TEST_DIR"
+    # exit status 0?
+if [ ${COMPILE_STATUS} -ne 0 ]; then
+    log_error "Test job failed to compile - Chapel is not installed correctly"
+    log_error "Compilation output:"
+    echo "${TEST_COMP_OUT}"
+    log_debug "Exit \"make check\" script with status code 1"
+    exit 1
+fi
 
-    $CHPL_HOME/util/start_test --no-chpl-home-warn --progress $CHPL_START_TEST_ARGS *.chpl > $test_output_log
+    # no errors on stdout/stderr?
+if [ -n "${TEST_COMP_OUT}" ]; then
+    # apply "prediff"-like filter to remove gmake "clock skew detected" warnings, if any
+    TEST_COMP_OUT=$( grep <<<"${TEST_COMP_OUT}" -v \
+        -e '^g*make\(\[[0-9]*\]\)*: Warning: File .* has modification time .* in the future *$' \
+        -e '^g*make\(\[[0-9]*\]\)*: warning:  Clock skew detected\.  Your build may be incomplete\. *$' )
+fi
 
-    test_status=$?
-    log_debug "start_test exit code: ${test_status}"
-)
-
-# Vars for capturing status info.
-success_key="^\[Success matching"
-error_key="^\[Error"
-warning_key="^\[Warning"
-summary_key="^\[Summary"
-summary_start_key="^\[Test Summary"
-
-function find_test_lines()
-{
-    local key="${1}"
-    local count_arg="${2}"
-
-    # Find the "[Start Summary ...]" line, then grep for $key after it. 100000
-    # is an arbitrarily large number that should include the rest of the file
-    # after [Start Summary ...].
-    grep -A100000 -E "${summary_start_key}" $test_output_log | \
-        grep $count_arg -E "${key}"
-}
-
-successes=$(grep -c -E "${success_key}" $test_output_log)
-errors=$(find_test_lines "${error_key}" -c)
-warnings=$(find_test_lines "${warning_key}" -c)
-
-log_debug "successes: ${successes}"
-log_debug "errors: ${errors}"
-log_debug "warnings: ${warnings}"
-
-# First, check for errors and warnings. Then make sure there was at least one success.
-if (( $errors )) && (( $errors > 0 )) ; then
-    log_error "${errors} tests failed:"
-    find_test_lines "${error_key}"
-    success=false
-elif (( $warnings )) && (( $warnings > 0 )) ; then
-    log_error "${warnings} tests produced warnings:"
-    find_test_lines "${warning_key}"
-    success=false
-elif (( $successes < 1 )) ; then
-    log_error "No tests ran."
-    success=false
+if [ -n "${TEST_COMP_OUT}" ]; then
+    log_error "Test job compiled with output - Chapel is not installed correctly"
+    log_error "Compilation output:"
+    echo "${TEST_COMP_OUT}"
+    log_debug "Exit \"make check\" script with status code 1"
+    exit 1
 else
-    success=true
+    log_info "Test job compiled into ${TMP_TEST_DIR}/${TEST_JOB}"
 fi
 
-# Print out the summary line.
-log_debug $(grep -E "${summary_key}" $test_output_log)
+# Find number of locales and .good file
+if [ ${chpl_comm} == "none" ]; then
+    NUMLOCALES=1
+    GOOD=${TEST_DIR}/${TEST_JOB}.comm-none.good
+else
+    NUMLOCALES="$(cat ${TEST_DIR}/NUMLOCALES)"
+    GOOD=${TEST_DIR}/${TEST_JOB}.good
+fi
 
-case $success in
-    true)
-        echo "chpl installation works as expected!"
+# Check for valid launchers
+if [ ${chpl_launcher} == "slurm-srun" -o ${chpl_launcher} == "amudprun" -o ${chpl_launcher} == "smp" -o ${chpl_launcher} == "none" ]; then
+    log_info "\$CHPL_LAUNCHER=${chpl_launcher} is compatible with test script."
+else
+    log_warning "\$CHPL_LAUNCHER=${chpl_launcher} is not compatible with test script."
+    log_warning "This does not necessarily indicate that your Chapel installation is incorrect."
+    log_warning "See \$CHPL_HOME/doc/rst/usingchapel/launcher.rst for information on manually launching Chapel programs."
+    # This exit code should be recognized as a failure to complete check, but
+    # not necessarily failure of build
+    log_debug "Exit \"make check\" script with status code 10"
+    exit 10
+fi
+
+TEST_EXEC_OUT=${TEST_JOB}.exec.out
+
+# Run compiled binary with parsed execution options
+(
+    cd ${TMP_TEST_DIR} || { log_error "failed cd ${TMP_TEST_DIR}" ; exit 1 ; }
+
+    EXEC_OPTS="$(cat ${TEST_DIR}/${TEST_JOB}.execopts)"
+
+    log_info "Running test job."
+    ./${TEST_JOB} -nl${NUMLOCALES} ${EXEC_OPTS} 2>&1 | sort > ${TEST_EXEC_OUT}
+    log_info "Test job complete."
+
+    # Check result
+    DIFF_OUTPUT=$(diff ${GOOD} ${TEST_EXEC_OUT})
+
+    # Return success code (0) if diff is good
+    if [ -z "${DIFF_OUTPUT}" ]; then
+        echo "SUCCESS: 'make check' passed!"
+        log_debug "Exit \"make check\" script with status code 0"
         exit 0
-        ;;
-    false|*)
-        # Print the log file if CHPL_CHECK_INSTALL_PRINT_ERROR is set to true.
-        if [ "${CHPL_CHECK_INSTALL_PRINT_ERROR}" = "true" ] ; then
-            cat $test_output_log
+    else
+        # Rerun test job with -v flag to help user identify discrepancy
+        log_error "There was an issue with the installation, test job output incorrect."
+        if [ "${CHPL_CHECK_DEBUG}" == 1 ] ; then
+            log_debug "Full test output is turned on, because \$CHPL_CHECK_DEBUG == 1"
+            echo ""
+            echo "== Reference Test output $( basename $GOOD ) =="
+            echo ""
+            head -100 $GOOD
+            echo ""
+            echo "== Actual Test Output (sorted to compare v. reference) =="
+            echo ""
+            head -100 ${TEST_EXEC_OUT}
+            echo ""
+            echo "== Difference =="
+            echo ""
+            diff ${GOOD} ${TEST_EXEC_OUT} | head -100
+            echo ""
+        else
+            log_info "To see the test outputs, export CHPL_CHECK_DEBUG=1 and re-run \"make check\""
         fi
 
-        echo "Found issues with chpl installation."
-        echo "  chpl path: ${CHPL_BIN}"
-        echo "  CHPL_HOME: ${CHPL_HOME}"
+        echo ""
+        echo "== Actual Test Output (raw, with verbose) =="
 
-        # Copy the output log file to a non-temp location to make it available
-        # for the user.
-        failure_log=$chpl_dir/$(basename $0)-failure.log
-        cp $test_output_log $failure_log
-        echo "Storing complete log in ${failure_log}"
+        ./${TEST_JOB} -nl${NUMLOCALES} ${EXEC_OPTS} -v
+        JOB_STATUS=$?
 
-        exit 10
-        ;;
-esac
+        log_debug "Test job exit status was ${JOB_STATUS}"
+
+        # This exit code should be recognized as successfully building, but
+        # with some errors
+        log_debug "Exit \"make check\" script with status code 20"
+        exit 20
+    fi
+)
